# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "ARTACK/debian-jessie"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "Hausehold assistant"
    vb.memory = 1024
    vb.customize ["modifyvm", :id, "--usb", "off"]
    vb.customize ["modifyvm", :id, "--usbehci", "off"]
    vb.customize ["modifyvm", :id, "--ioapic", "on", "--audio", "alsa", "--audiocontroller", "ac97"]
    vb.customize ["modifyvm", :id, "--pae", "on"]
  end

  config.vm.provision :ansible do |ansible|
    ansible.playbook = "ansible/deploy.yml"
  end

end
